[2022-11-30 05:48:09,469] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: vaccine_dags.creatableLoad scheduled__2022-11-29T00:00:00+00:00 [queued]>
[2022-11-30 05:48:09,475] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: vaccine_dags.creatableLoad scheduled__2022-11-29T00:00:00+00:00 [queued]>
[2022-11-30 05:48:09,476] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-11-30 05:48:09,476] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-11-30 05:48:09,476] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-11-30 05:48:09,485] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): creatableLoad> on 2022-11-29 00:00:00+00:00
[2022-11-30 05:48:09,487] {standard_task_runner.py:52} INFO - Started process 5959 to run task
[2022-11-30 05:48:09,490] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'vaccine_dags', 'creatableLoad', 'scheduled__2022-11-29T00:00:00+00:00', '--job-id', '1407', '--raw', '--subdir', 'DAGS_FOLDER/vaccine.py', '--cfg-path', '/tmp/tmp7bo8da7a', '--error-file', '/tmp/tmpk6a36ic1']
[2022-11-30 05:48:09,491] {standard_task_runner.py:77} INFO - Job 1407: Subtask creatableLoad
[2022-11-30 05:48:09,529] {logging_mixin.py:109} INFO - Running <TaskInstance: vaccine_dags.creatableLoad scheduled__2022-11-29T00:00:00+00:00 [running]> on host acb48b0a6e0d
[2022-11-30 05:48:09,566] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=vaccine_dags
AIRFLOW_CTX_TASK_ID=creatableLoad
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-29T00:00:00+00:00
[2022-11-30 05:48:09,648] {python.py:175} INFO - Done. Returned value was: None
[2022-11-30 05:48:09,657] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=vaccine_dags, task_id=creatableLoad, execution_date=20221129T000000, start_date=20221130T054809, end_date=20221130T054809
[2022-11-30 05:48:09,703] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-11-30 05:48:09,726] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
