[2022-11-29 14:00:14,849] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: vaccine_dags.getDataToLocal manual__2022-11-29T14:00:13.819849+00:00 [queued]>
[2022-11-29 14:00:14,861] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: vaccine_dags.getDataToLocal manual__2022-11-29T14:00:13.819849+00:00 [queued]>
[2022-11-29 14:00:14,861] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-11-29 14:00:14,861] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-11-29 14:00:14,861] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-11-29 14:00:14,876] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): getDataToLocal> on 2022-11-29 14:00:13.819849+00:00
[2022-11-29 14:00:14,881] {standard_task_runner.py:52} INFO - Started process 344 to run task
[2022-11-29 14:00:14,885] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'vaccine_dags', 'getDataToLocal', 'manual__2022-11-29T14:00:13.819849+00:00', '--job-id', '1168', '--raw', '--subdir', 'DAGS_FOLDER/vaccine.py', '--cfg-path', '/tmp/tmp8v_w7mbh', '--error-file', '/tmp/tmpzlwmzdla']
[2022-11-29 14:00:14,885] {standard_task_runner.py:77} INFO - Job 1168: Subtask getDataToLocal
[2022-11-29 14:00:14,942] {logging_mixin.py:109} INFO - Running <TaskInstance: vaccine_dags.getDataToLocal manual__2022-11-29T14:00:13.819849+00:00 [running]> on host acb48b0a6e0d
[2022-11-29 14:00:14,998] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=vaccine_dags
AIRFLOW_CTX_TASK_ID=getDataToLocal
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T14:00:13.819849+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-29T14:00:13.819849+00:00
[2022-11-29 14:00:15,549] {python.py:175} INFO - Done. Returned value was: None
[2022-11-29 14:00:15,561] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=vaccine_dags, task_id=getDataToLocal, execution_date=20221129T140013, start_date=20221129T140014, end_date=20221129T140015
[2022-11-29 14:00:15,619] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-11-29 14:00:15,718] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
