[2022-11-29 02:30:01,587] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: Covid_dags.creatableLoad manual__2022-11-29T02:24:52.196930+00:00 [queued]>
[2022-11-29 02:30:01,600] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: Covid_dags.creatableLoad manual__2022-11-29T02:24:52.196930+00:00 [queued]>
[2022-11-29 02:30:01,600] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-11-29 02:30:01,600] {taskinstance.py:1244} INFO - Starting attempt 2 of 2
[2022-11-29 02:30:01,600] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-11-29 02:30:01,612] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): creatableLoad> on 2022-11-29 02:24:52.196930+00:00
[2022-11-29 02:30:01,617] {standard_task_runner.py:52} INFO - Started process 1100 to run task
[2022-11-29 02:30:01,620] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Covid_dags', 'creatableLoad', 'manual__2022-11-29T02:24:52.196930+00:00', '--job-id', '889', '--raw', '--subdir', 'DAGS_FOLDER/dbtest.py', '--cfg-path', '/tmp/tmpybuy3g37', '--error-file', '/tmp/tmp_tyq2skp']
[2022-11-29 02:30:01,621] {standard_task_runner.py:77} INFO - Job 889: Subtask creatableLoad
[2022-11-29 02:30:01,675] {logging_mixin.py:109} INFO - Running <TaskInstance: Covid_dags.creatableLoad manual__2022-11-29T02:24:52.196930+00:00 [running]> on host acb48b0a6e0d
[2022-11-29 02:30:01,728] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Covid_dags
AIRFLOW_CTX_TASK_ID=creatableLoad
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T02:24:52.196930+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-29T02:24:52.196930+00:00
[2022-11-29 02:30:01,881] {python.py:175} INFO - Done. Returned value was: None
[2022-11-29 02:30:01,891] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=Covid_dags, task_id=creatableLoad, execution_date=20221129T022452, start_date=20221129T023001, end_date=20221129T023001
[2022-11-29 02:30:01,912] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-11-29 02:30:01,940] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
