[2022-11-29 14:17:36,422] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: vaccine_dags.creatableLoad manual__2022-11-29T14:12:30.925489+00:00 [queued]>
[2022-11-29 14:17:36,430] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: vaccine_dags.creatableLoad manual__2022-11-29T14:12:30.925489+00:00 [queued]>
[2022-11-29 14:17:36,431] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-11-29 14:17:36,431] {taskinstance.py:1244} INFO - Starting attempt 2 of 2
[2022-11-29 14:17:36,431] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-11-29 14:17:36,442] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): creatableLoad> on 2022-11-29 14:12:30.925489+00:00
[2022-11-29 14:17:36,447] {standard_task_runner.py:52} INFO - Started process 1173 to run task
[2022-11-29 14:17:36,449] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'vaccine_dags', 'creatableLoad', 'manual__2022-11-29T14:12:30.925489+00:00', '--job-id', '1221', '--raw', '--subdir', 'DAGS_FOLDER/vaccine.py', '--cfg-path', '/tmp/tmpfoezvlkb', '--error-file', '/tmp/tmpr4o3vrm_']
[2022-11-29 14:17:36,450] {standard_task_runner.py:77} INFO - Job 1221: Subtask creatableLoad
[2022-11-29 14:17:36,502] {logging_mixin.py:109} INFO - Running <TaskInstance: vaccine_dags.creatableLoad manual__2022-11-29T14:12:30.925489+00:00 [running]> on host acb48b0a6e0d
[2022-11-29 14:17:36,546] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=vaccine_dags
AIRFLOW_CTX_TASK_ID=creatableLoad
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T14:12:30.925489+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-29T14:12:30.925489+00:00
[2022-11-29 14:17:36,663] {python.py:175} INFO - Done. Returned value was: None
[2022-11-29 14:17:36,677] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=vaccine_dags, task_id=creatableLoad, execution_date=20221129T141230, start_date=20221129T141736, end_date=20221129T141736
[2022-11-29 14:17:36,702] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-11-29 14:17:36,732] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
