[2022-11-29 02:28:31,110] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: Covid_dags.creatableLoad manual__2022-11-29T02:23:22.874495+00:00 [queued]>
[2022-11-29 02:28:31,116] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: Covid_dags.creatableLoad manual__2022-11-29T02:23:22.874495+00:00 [queued]>
[2022-11-29 02:28:31,116] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-11-29 02:28:31,116] {taskinstance.py:1244} INFO - Starting attempt 2 of 2
[2022-11-29 02:28:31,116] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-11-29 02:28:31,124] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): creatableLoad> on 2022-11-29 02:23:22.874495+00:00
[2022-11-29 02:28:31,128] {standard_task_runner.py:52} INFO - Started process 1019 to run task
[2022-11-29 02:28:31,131] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Covid_dags', 'creatableLoad', 'manual__2022-11-29T02:23:22.874495+00:00', '--job-id', '885', '--raw', '--subdir', 'DAGS_FOLDER/dbtest.py', '--cfg-path', '/tmp/tmp1vo5fggu', '--error-file', '/tmp/tmp89ylos2d']
[2022-11-29 02:28:31,131] {standard_task_runner.py:77} INFO - Job 885: Subtask creatableLoad
[2022-11-29 02:28:31,171] {logging_mixin.py:109} INFO - Running <TaskInstance: Covid_dags.creatableLoad manual__2022-11-29T02:23:22.874495+00:00 [running]> on host acb48b0a6e0d
[2022-11-29 02:28:31,210] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Covid_dags
AIRFLOW_CTX_TASK_ID=creatableLoad
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T02:23:22.874495+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-29T02:23:22.874495+00:00
[2022-11-29 02:28:31,346] {python.py:175} INFO - Done. Returned value was: None
[2022-11-29 02:28:31,354] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=Covid_dags, task_id=creatableLoad, execution_date=20221129T022322, start_date=20221129T022831, end_date=20221129T022831
[2022-11-29 02:28:31,383] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-11-29 02:28:31,405] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
