[2022-11-29 14:10:34,790] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: vaccine_dags.transformData manual__2022-11-29T14:05:29.887577+00:00 [queued]>
[2022-11-29 14:10:34,801] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: vaccine_dags.transformData manual__2022-11-29T14:05:29.887577+00:00 [queued]>
[2022-11-29 14:10:34,801] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-11-29 14:10:34,802] {taskinstance.py:1244} INFO - Starting attempt 2 of 2
[2022-11-29 14:10:34,802] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-11-29 14:10:34,818] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): transformData> on 2022-11-29 14:05:29.887577+00:00
[2022-11-29 14:10:34,823] {standard_task_runner.py:52} INFO - Started process 836 to run task
[2022-11-29 14:10:34,827] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'vaccine_dags', 'transformData', 'manual__2022-11-29T14:05:29.887577+00:00', '--job-id', '1203', '--raw', '--subdir', 'DAGS_FOLDER/vaccine.py', '--cfg-path', '/tmp/tmp6ibj43r1', '--error-file', '/tmp/tmpzzgd5q8v']
[2022-11-29 14:10:34,828] {standard_task_runner.py:77} INFO - Job 1203: Subtask transformData
[2022-11-29 14:10:34,888] {logging_mixin.py:109} INFO - Running <TaskInstance: vaccine_dags.transformData manual__2022-11-29T14:05:29.887577+00:00 [running]> on host acb48b0a6e0d
[2022-11-29 14:10:34,952] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=vaccine_dags
AIRFLOW_CTX_TASK_ID=transformData
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T14:05:29.887577+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-29T14:05:29.887577+00:00
[2022-11-29 14:10:34,984] {python.py:175} INFO - Done. Returned value was: None
[2022-11-29 14:10:35,000] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=vaccine_dags, task_id=transformData, execution_date=20221129T140529, start_date=20221129T141034, end_date=20221129T141035
[2022-11-29 14:10:35,039] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-11-29 14:10:35,245] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
