[2022-11-28 19:17:52,271] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: using_pandas_demo.creatableLoad manual__2022-11-28T19:17:46.812256+00:00 [queued]>
[2022-11-28 19:17:52,283] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: using_pandas_demo.creatableLoad manual__2022-11-28T19:17:46.812256+00:00 [queued]>
[2022-11-28 19:17:52,283] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-11-28 19:17:52,283] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2022-11-28 19:17:52,283] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-11-28 19:17:52,302] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): creatableLoad> on 2022-11-28 19:17:46.812256+00:00
[2022-11-28 19:17:52,308] {standard_task_runner.py:52} INFO - Started process 1006 to run task
[2022-11-28 19:17:52,312] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'using_pandas_demo', 'creatableLoad', 'manual__2022-11-28T19:17:46.812256+00:00', '--job-id', '422', '--raw', '--subdir', 'DAGS_FOLDER/dbtest.py', '--cfg-path', '/tmp/tmp8tmtq832', '--error-file', '/tmp/tmp1bfkb9yf']
[2022-11-28 19:17:52,313] {standard_task_runner.py:77} INFO - Job 422: Subtask creatableLoad
[2022-11-28 19:17:52,381] {logging_mixin.py:109} INFO - Running <TaskInstance: using_pandas_demo.creatableLoad manual__2022-11-28T19:17:46.812256+00:00 [running]> on host acb48b0a6e0d
[2022-11-28 19:17:52,446] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=using_pandas_demo
AIRFLOW_CTX_TASK_ID=creatableLoad
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T19:17:46.812256+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-28T19:17:46.812256+00:00
[2022-11-28 19:17:52,654] {python.py:175} INFO - Done. Returned value was: None
[2022-11-28 19:17:52,666] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=using_pandas_demo, task_id=creatableLoad, execution_date=20221128T191746, start_date=20221128T191752, end_date=20221128T191752
[2022-11-28 19:17:52,684] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-11-28 19:17:52,714] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
